# Age Group Mappings (German <-> Internal ID)
[age_groups]
"Hgr" = "adult"
"Hgr." = "adult"
"Hgr.II" = "adult_2"
"Hgr II" = "adult_2"
"Sen" = "senior"
"Sen." = "senior"
"Sen.I" = "sen_1"
"Sen.II" = "sen_2"
"Sen.III" = "sen_3"
"Sen.IV" = "sen_4"
"Sen.V" = "sen_5"
"Kinder I" = "juv_1"
"Kinder II" = "juv_2"
"Kin." = "juv"
"Kin.I" = "juv_1"
"Kin.II" = "juv_2"
"Junioren I" = "jun_1"
"Junioren II" = "jun_2"
"Jun.I" = "jun_1"
"Jun.II" = "jun_2"
"Jugend" = "youth"
"Jug." = "youth"
"Hauptgruppe" = "adult"
"Adult" = "adult"
"Adults" = "adult"
"Rising Stars" = "adult"
"Mas." = "senior"
"Mas.I" = "sen_1"
"Mas.II" = "sen_2"
"Mas.III" = "sen_3"
"Mas.IV" = "sen_4"
"Mas.V" = "sen_5"
"Hauptgruppe II" = "adult_2"
"Senioren I" = "sen_1"
"Senioren II" = "sen_2"
"Senioren III" = "sen_3"
"Senioren IV" = "sen_4"
"Senioren V" = "sen_5"

# Dance/Discipline Mappings
[dances]
"Standard" = "std"
"Latein" = "lat"
"Latin" = "lat"
"SW" = "slow_waltz"
"LW" = "slow_waltz"
"Walzer" = "slow_waltz"
"TG" = "tango"
"Tango" = "tango"
"VW" = "viennese_waltz"
"Wiener Walzer" = "viennese_waltz"
"SF" = "slow_foxtrot"
"Slowfox" = "slow_foxtrot"
"QS" = "quickstep"
"Quickstep" = "quickstep"
"CC" = "cha_cha_cha"
"Cha Cha" = "cha_cha_cha"
"SB" = "samba"
"Samba" = "samba"
"RB" = "rumba"
"Rumba" = "rumba"
"PD" = "paso_doble"
"Paso Doble" = "paso_doble"
"JV" = "jive"
"Jive" = "jive"

# Role Mappings
[roles]
"Turnierleiter" = "responsible_person"
"Beisitzer" = "assistant"
